button_card_templates: !include button_card_templates.yaml

resources:
  - url: /browser_mod.js
    type: module
  - url: /local/light-entity-card/dist/light-entity-card.js
    type: js    
  - url: /hacsfiles/hass-shutter-card/hass-shutter-card.js
    type: module    
  - url: /hacsfiles/apexcharts-card/apexcharts-card.js
    type: module       
kiosk_mode:
  user_settings:
    - users:
        - "touch"
      hide_sidebar: true
      hide_header: true
     
views: 
  - title: Control Rooms
    icon: 'mdi:floor-plan'
    type: custom:grid-layout
    layout:
      grid-template-columns: 120px 120px 120px 120px 84px 156px 120px 120px 
      grid-template-rows: 134px 265px 110px 110px 75px 1000px 34px
      grid-template-areas: |
        "header2 header2 header3 header3 header1 header1 header4 header4"
        "a a a a a meteo meteo meteo"
        "2 2 2 2 2 gr gr gr"
        "2 2 2 2 2 gr gr gr"
        "gr2 gr2 gr2 gr2 gr2 gr2 gr2 gr2"
        "footer footer footer footer footer footer footer footer"     
        "menu menu menu menu menu menu menu menu"
    cards:
      - type: 'custom:button-card'
        entity: sensor.time
        layout: vertical
        show_icon: false
        show_label: true
        show_name: false
        show_state: true
        styles:
          card:
            - height: 125px
          state:
            - font-size: 400%
            - font-weight: bold
            - justify-self: center
          label:
            - justify-self: center
            - font-size: 90%
            - color: var(--paper-item-icon-active-color)
          name:
            - justify-self: center
            - font-size: 120%
        tap_action:
          action: none        
        view_layout:          
           grid-area: header2          

      - type: energy-grid-neutrality-gauge
        view_layout:       
           grid-area: header3    


           
      - type: gauge
        entity: sensor.consumo_power
        min: 0
        severity:
          green: 0
          yellow: 0
          red: 1
        max: 6000
        name: CONSUMO            
        view_layout:          
           grid-area: header4
           
      - type: gauge
        entity: sensor.solaredge_current_power
        max: 5998
        min: 0
        severity:
          green: 0
          yellow: 1
          red: -1
        name: FOTOVOLTAICO      
        view_layout:
           grid-area: header1
           
      - type: horizontal-stack
        cards:
          - !include touch/home/grafico_energy.yaml
        view_layout:       
           grid-area: gr           

      - type: horizontal-stack
        cards:
          - !include touch/home/grafico_energy2.yaml
        view_layout:       
           grid-area: gr2
           
           
           
      - type: custom:mini-media-player       
        entity: media_player.soggiorno
        group: false
        volume_stateless: false
        artwork: full-cover
        source: full
        sound_mode: full
        info: short
        replace_mute: play_pause
        view_layout:       
           grid-area: a   
           
           
      - type: horizontal-stack
        cards:
          - !include touch/home/meteo.yaml
        view_layout:       
           grid-area: meteo  

           
           
      - type: horizontal-stack
        cards:
          - !include touch/home/menu.yaml 
        view_layout:       
           grid-area: menu
           
      - type: 'custom:mod-card'
        style:
          swipe-card:
            $: |
              .swiper-pagination {
                top: 2px;
                height: 1vw; 
                }
        card:
          type: 'custom:swipe-card'
          parameters:
            effect: fade
            EffectFade:
             
          cards:
            - !include touch/home/3d2.yaml 
            - !include touch/home/dispositivi.yaml
        view_layout:       
           grid-area: footer 
           
           








#################################################################################################################################################    

  - title: kronoterm
    icon: 'mdi:water-outline'
    type: custom:grid-layout
    layout:
      grid-template-columns: 140px 127px 127px 127px 127px 127px 127px 127px
      grid-template-rows: 677px 1060px 60px
      grid-template-areas: |
        "pdc pdc pdc pdc pdc pdc pdc pdc"
        "footer footer footer footer footer footer footer footer" 
        "menu menu menu menu menu menu menu menu"
        
    cards:     
      - type: horizontal-stack
        cards:
          - !include touch/home/kronoterm.yaml 
        view_layout:       
           grid-area: pdc             
      - type: horizontal-stack
        cards:
          - !include touch/home/menu.yaml 
        view_layout:       
           grid-area: menu 
      - type: horizontal-stack
        cards:
          - !include touch/home/3d.yaml 
        view_layout:       
           grid-area: footer              
              

              
