
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  packages: !include_dir_named packages   
  
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


lovelace:
  mode: storage
  dashboards:
    lovelace-touch:
      mode: yaml
      title: Tuoch2
      icon: mdi:tablet
      show_in_sidebar: true
      filename: lovelace-touch.yaml 
      
