automation:

  - alias: 'cucina on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 33
          pushbutton: 1
    action:
      - service: myhome.send_message
        data:
          message: '*1*1*02##'
      - service: light.turn_on
        data:
         entity_id: light.lampadario_cucina
         brightness: 255
         kelvin: 4000

  - alias: 'cucina off'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 33
          pushbutton: 2
    action:
      - service: light.turn_off
        data:
         entity_id: light.lampadario_cucina
      - service: myhome.send_message
        data:
          message: '*1*0*02##'        
         
  - alias: 'colore cucina'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_long_press 
          object: 33
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.lampadario_cucina
         effect: random
         transition: 2

  - alias: 'faretti cucina 1 on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 33
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.faretti_piano_cotura
         brightness: 255
         kelvin: 4000

  - alias: 'faretti cucina 1 off'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 33
          pushbutton: 2
    action:
      - service: light.turn_off
        data:
         entity_id: light.faretti_piano_cotura
         
  - alias: 'camera greta on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 16
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_greta
         brightness: 255
         kelvin: 4000

  - alias: 'camera greta off'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 16
          pushbutton: 2
    action:
      - service: light.turn_off
        data:
         entity_id: light.hue_camera_greta
         
  - alias: 'camera greta blue'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 15
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_greta
         brightness: 255
         color_name: blue

  - alias: 'camera greta viola'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 15
          pushbutton: 2
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_greta
         color_name: purple 

  - alias: 'camera creta luci calde'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 14
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_greta
         brightness: 100
         kelvin: 2500

  - alias: 'camera creta colorloop'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_long_press 
          object: 15
          pushbutton: 1
    action:
      - service: lifx.effect_colorloop
        data:
         entity_id: light.hue_camera_greta    
         brightness: 225
         period: 5
         spread: 30
         change: 35
         
  - alias: 'camera greta colorloop stop'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_long_release
          object: 15
          pushbutton: 1
    action:
      - service: lifx.effect_stop
        data:
         entity_id: light.hue_camera_greta

  - alias: 'camera bianca on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 11
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_bianca
         brightness: 255
         kelvin: 4000

  - alias: 'camera bianca off'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 11
          pushbutton: 2
    action:
      - service: light.turn_off
        data:
         entity_id: light.hue_camera_bianca
         
  - alias: 'camera bianca blue'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 12
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_bianca
         brightness: 255
         color_name: blue

  - alias: 'camera cìbianca viola'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 12
          pushbutton: 2
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_bianca
         color_name: purple 

  - alias: 'camera bianca luci calde'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 13
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.hue_camera_bianca
         brightness: 100
         kelvin: 2500

  - alias: 'camera bianca colorloop'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_long_press 
          object: 13
          pushbutton: 1
    action:
      - service: lifx.effect_colorloop
        data:
         entity_id: light.hue_camera_bianca   
         brightness: 225
         period: 5
         spread: 30
         change: 35
         
  - alias: 'camera bianca colorloop stop'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_long_release
          object: 13
          pushbutton: 1
    action:
      - service: lifx.effect_stop
        data:
         entity_id: light.hue_camera_bianca       
         
  - alias: 'salotto on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data:
          event: pushbutton_short_press 
          object: 41
          pushbutton: 1
    action:
      - service: light.turn_on
        data:
         entity_id: light.faretti_salotto
         brightness: 255
         kelvin: 4000

  - alias: 'salotto off'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event 
        event_data: 
          event: pushbutton_short_press 
          object: 43
          pushbutton: 1
    action:
      - service: light.turn_off
        data:
         entity_id: light.faretti_salotto         

  - alias: 'luci my on'
    trigger:         
      - platform: event
        event_type: myhome_general_light_event
        event_data:
          event: on         