automation:

  - alias: 'dimmer cucina up'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 1
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: up
            light: light.lampadario_cucina

  - alias: 'dimmer cucina down'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 2
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: down
            light: light.lampadario_cucina

  - alias: 'Stop dimmer cucina'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 1
          event: pushbutton_long_release
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 2
          event: pushbutton_long_release
    action:
      - service: script.turn_off
        entity_id: script.ramp_light
        
  - alias: 'dimmer faretti piano cottura up'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 1
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: up
            light: light.faretti_piano_cotura

  - alias: 'dimmer faretti piano cotura down'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 2
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: down
            light: light.faretti_piano_cotura

  - alias: 'Stop dimmer faretti piano cottura'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 1
          event: pushbutton_long_release
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 33
          pushbutton: 2
          event: pushbutton_long_release
    action:
      - service: script.turn_off
        entity_id: script.ramp_light

  - alias: 'dimmer camera greta up'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 16
          pushbutton: 1
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: up
            light: light.hue_camera_greta

  - alias: 'dimmer camera greta down'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 16
          pushbutton: 2
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: down
            light: light.hue_camera_greta

  - alias: 'Stop dimmer camera greta'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 16
          pushbutton: 1
          event: pushbutton_long_release
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 16
          pushbutton: 2
          event: pushbutton_long_release
    action:
      - service: script.turn_off
        entity_id: script.
        
  - alias: 'dimmer camera bianca up'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 11
          pushbutton: 1
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: up
            light: light.hue_camera_bianca

  - alias: 'dimmer camera bianca down'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 11
          pushbutton: 2
          event: pushbutton_long_press
    action:
      - service: script.turn_on
        entity_id: script.ramp_light
        data:
          variables:
            direction: down
            light: light.hue_camera_bianca

  - alias: 'Stop dimmer camera bianca'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 11
          pushbutton: 1
          event: pushbutton_long_release
      - platform: event
        event_type: myhome_cenplus_event
        event_data:
          object: 11
          pushbutton: 2
          event: pushbutton_long_release
    action:
      - service: script.turn_off
        entity_id: script.ramp_light        
        
        
        
input_number:
  light_step:
    name: 'Step the lights this much'
    initial: 25
    min: 1
    max: 64
    step: 1

  light_minimum:
    name: 'No dimmer than this'
    initial: 5
    min: 1
    max: 255
    step: 1

  light_maximum:
    name: 'No brighter than this'
    initial: 255
    min: 50
    max: 255
    step: 1

  light_delay_ms:
    name: 'Step the lights this often (ms)'
    initial: 100
    min: 100
    max: 5000
    step: 100

script:
  ramp_light:
    alias: Ramp Light Brightness
    description: Ramp light brightness up or down
    fields:
      direction:
        description: "Direction to change brightness: up or down"
        example: up
      light:
        description: light.plafoniera_cameretta
        example: light.family_room_lamp
    mode: restart
    sequence:
      - repeat:
          while:
            - condition: template
              value_template: >
                {% set br = state_attr(light, 'brightness')|int(0) %}
                {% set mn = states('input_number.light_minimum')|int %}
                {% set mx = states('input_number.light_maximum')|int %}
                {{ direction == 'up' and br < mx or
                   direction == 'down' and br > mn }}
          sequence:
            - service: light.turn_on
              data:
                entity_id: "{{ light }}"
                brightness: >
                  {% set br = state_attr(light, 'brightness')|int(0) %}
                  {% set mn = states('input_number.light_minimum')|int %}
                  {% set mx = states('input_number.light_maximum')|int %}
                  {% set st = states('input_number.light_step')|int %}
                  {% if direction == 'up' %}
                    {{ [br + st, mx]|min }}
                  {% else %}
                    {{ [br - st, mn]|max }}
                  {% endif %}
            - delay:
                milliseconds: "{{ states('input_number.light_delay_ms')|int }}"
