sensor:
  - platform: integration
    source: sensor.solaredge_current_power
    name: energy_spent
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.solaredge_grid_power
    name: energy_grid
    unit_prefix: k
    round: 2    
        