sensor:
    
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
    

  - platform: systemmonitor
    resources:
      - type: memory_free
      
      - type: disk_use
      
      - type: disk_free
        
      - type: processor_use
     
      - type: memory_use
      
      - type: memory_use_percent
        
      - type: disk_use_percent
     
      - type: ipv4_address
        arg: eth0
     
      - type: last_boot
      
  - platform: template
    sensors:
      disk_total:
        value_template: "{{ ( states('sensor.disk_use')|float + states('sensor.disk_free')|float )| round (1) }}"
      

      



    
