sensor:

#######termostato salotto#####################
  - platform: template 
    sensors: 
    
    
      umidita_salotto:
        friendly_name: "umidita salotto"
        value_template: >-
          {{states.climate.termostato_soggiorno.attributes.current_humidity|float}}   
        icon_template: mdi:water-percent  
  
      temperatura_salotto:
        friendly_name: "temperatura salotto"
        value_template: >-
          {{states.climate.termostato_soggiorno.attributes.current_temperature|float}}   
        icon_template: mdi:thermometer  
